name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.5

      - name: Install Dependencies
        run: |
          npm install
          npm ls

      - name: Build
        run: npm run build

      - name: Test
        run: echo "No tests specified" #or npm run test
